CREATE TABLE TICKET
(
    id                    serial,
    type                  varchar(30),
    code                  varchar(30),
    opening_price         double precision,
    high_price            double precision,
    low_price             double precision,
    trade_price           double precision,
    prev_closing_price    double precision,
    change                varchar(30),
    change_price          double precision,
    signed_change_price   double precision,
    change_rate           double precision,
    signed_change_rate    double precision,
    trade_volume          double precision,
    acc_trade_volume      double precision,
    acc_trade_volume_24h  double precision,
    acc_trade_price       double precision,
    acc_trade_price_24h   double precision,
    trade_date            varchar(30),
    trade_time            varchar(30),
    trade_timestamp       int,
    ask_bid               varchar(30),
    acc_ask_volume        double precision,
    acc_bid_volume        double precision,
    highest_52_week_price double precision,
    highest_52_week_date  varchar(30),
    lowest_52_week_price  double precision,
    lowest_52_week_date   varchar(30),
    trade_status          varchar(30),
    market_state          varchar(30),
    market_state_for_ios  varchar(30),
    is_trading_suspended  varchar(30),
    delisting_date        date,
    market_warning        varchar(30),
    timestamp             int,
    stream_type           varchar(30)
);